project:
  type: website

website:
  title: "Blog"
  description: "This is Lauren Van Blarcum personal Blog."
  navbar:
    right:
      - text: Blog
        href: blog.qmd 
      - icon: github
        href: https://laurenvanblarcum.github.io/
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

